# Generated by Django 2.2.6 on 2019-11-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Clothes', 'Clothes'), ('RTV', 'RTV'), ('Household Goods', 'Household Goods')], default=0, max_length=50, verbose_name='Data:')),
                ('description', models.CharField(max_length=50, verbose_name='Description:')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Cost:')),
                ('date', models.DateField(verbose_name='Date:')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
